"""empty message

Revision ID: dff5aea719bb
Revises: 
Create Date: 2024-01-31 15:47:00.094586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff5aea719bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loadlevelheight3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loadstarttime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('loadtime3', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic', schema=None) as batch_op:
        batch_op.drop_column('loadtime3')
        batch_op.drop_column('loadstarttime')
        batch_op.drop_column('loadlevelheight3')

    # ### end Alembic commands ###
